[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
evm_version = "paris"         # make sure Sei EVM supports this
optimizer = true
optimizer_runs = 200
via_ir = true                  # enable via-IR to avoid "stack too deep" issues

[rpc_endpoints]
sei = "${SEI_RPC_URL}"
